apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rosette-server.fullname" . }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rosette-server.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "rosette-server.fullname" . }}-patch-deployment-sa