apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rosette-server.fullname" . }}-patch-deployment-sa
  labels:
    {{- include "rosette-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
