apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rosette-server.fullname" . }}-conf
  labels: {{- include "rosette-server.labels" . | nindent 4 }}
data:
{{ .Values.conf | toYaml | indent 2 }}