apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rosette-server.fullname" . }}-rosapi
  labels: {{- include "rosette-server.labels" . | nindent 4 }}
data:
{{ .Values.rosapi | toYaml | indent 2 }}