#******************************************************************************
# This data and information is proprietary to, and a valuable trade secret
# of, Basis Technology Corp.  It is given in confidence by Basis Technology
# and may only be used as permitted under the license agreement under which
# it has been distributed, and in no other way.
#
# Copyright (c) 2023 Basis Technology Corporation All rights reserved.
#
# The technical data and information provided herein are provided with
# `limited rights', and the computer software provided herein is provided
# with `restricted rights' as those terms are defined in DAR and ASPR
# 7-104.9(a).
#******************************************************************************
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "rosette-server.fullname" . }}-roots-volume
  labels:
    {{- include "rosette-server.labels" . | nindent 4 }}
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  {{- if .Values.storage.nfs.enabled }}
  capacity:
    storage: {{ .Values.storage.nfs.roots.storageCapacity }}
  storageClassName: {{ .Values.storage.nfs.storageClassName }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.storage.nfs.roots.mountPoint }}
    server: {{ .Values.storage.nfs.address }}
  {{- else if .Values.storage.persistentDisk.enabled }}
  capacity:
    storage: {{ .Values.storage.persistentDisk.roots.capacity }}
  storageClassName: {{ .Values.storage.persistentDisk.roots.storageClassName }}
  csi:
    driver: {{ .Values.storage.persistentDisk.roots.driver }}
    volumeHandle: {{ .Values.storage.persistentDisk.roots.volume }}
    fsType: {{ .Values.storage.persistentDisk.roots.fsType  }}
  {{- end }}
