apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rosent-pv.fullname" . }}-config-rosapi
  labels:
    {{- include "rosent-pv.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "config/rosapi/*").AsConfig | indent 2 }}