apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rosent-pv.fullname" . }}
  labels:
    {{- include "rosent-pv.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rosent-pv.fullname" . }}
  minReplicas: {{ .Values.horizontalLoadBalancer.targetMinReplicas }}
  maxReplicas: {{ .Values.horizontalLoadBalancer.targetMaxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.horizontalLoadBalancer.targetCPUUtilizationPercent }}