apiVersion: v1
kind: Service
metadata:
  name: {{ include "rosent-pv.fullname" . }}
  labels:
    {{- include "rosent-pv.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rosent-pv.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
  sessionAffinity: {{ .Values.loadbalancer.sessionAffinity }}
  ports:
    - port: {{ .Values.loadbalancer.port }}
      targetPort: {{ .Values.rosentimage.port }}
      protocol: TCP
      name: http
  