apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rosent-pv.fullname" . }}-roots
  labels:
    {{- include "rosent-pv.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "rosent-pv.selectorLabels" . | nindent 6 }}
  storageClassName: default
  volumeName: {{ include "rosent-pv.fullname" . }}-roots
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100G