apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "rosent-pv.fullname" . }}-roots
  labels:
    {{- include "rosent-pv.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 100G
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.nfsServer.rootsMountPoint }}
    server: {{ .Values.nfsServer.address }}
