#******************************************************************************
# This data and information is proprietary to, and a valuable trade secret
# of, Basis Technology Corp.  It is given in confidence by Basis Technology
# and may only be used as permitted under the license agreement under which
# it has been distributed, and in no other way.
#
# Copyright (c) 2023 Basis Technology Corporation All rights reserved.
#
# The technical data and information provided herein are provided with
# `limited rights', and the computer software provided herein is provided
# with `restricted rights' as those terms are defined in DAR and ASPR
# 7-104.9(a).
#******************************************************************************

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rosette-server.fullname" . }}-config-rosapi-configmap
  labels:
    {{- include "rosette-server.labels" . | nindent 4 }}
data:
{{- $path := printf "%s/*" .Values.rosetteServer.configRosapiDirectory }}
{{ (.Files.Glob $path).AsConfig | indent 2 }}